### ISSUE TITLE
Disable ansi escapes

### ISSUE THREAD

**Issue by d10xa** [com-lihaoyi/fansi#31]
Is it possible to disable escapes for range of symbols? It is inconvenient to use tools such ammonite or almond when there are ansi codes instead of Russian letters

<img width="384" alt="amm 2021-03-03 14-13-40" src="https://user-images.githubusercontent.com/10722234/109797557-aeea6680-7c2a-11eb-9efe-e6cc94069f64.png">
<img width="840" alt="Fansi scala — fansi 2021-03-03 14-14-36" src="https://user-images.githubusercontent.com/10722234/109797672-d04b5280-7c2a-11eb-818c-4b19b831c23b.png">

**Comment by lihaoyi** [comment]
This is in the wrong repo. It's a in issue with PPrint which is fixed in master
